=== Locwara/CNXML_CN/BUOI_4/2/sv.xsd
<?xml version="1.0" encoding="UTF-8"?>  
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="MaType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10"/>
            <xs:pattern value="[A-Z0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TenKhoa">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20"/>
            <xs:pattern value="[A-Z0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TenLop">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sdtType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{10}"/>
        </xs:restriction>
    </xs:simpleType>

    
    <xs:element name="school">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sinhvien" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mssv" type="xs:string"/>
                            <xs:element name="hoten" type = "xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="diachi" type = "xs:string"/>
                            <xs:element name="sdt" type="sdtType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lop" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ma" type = "MaType"/>
                            <xs:element name="ten" type = "TenLop"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="khoa" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ma" type = "MaType"/>
                            <xs:element name="ten" type = "TenKhoa"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="thuoc" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mssv_Ref" type="xs:string"/>
                            <xs:element name="ma_lop_Ref" type="MaType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="quanly" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ma_lop_Ref" type="MaType"/>
                            <xs:element name = "ma_khoa_Ref" type="MaType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="LopKey">
            <xs:selector xpath="lop"/>
            <xs:field xpath="ma"/>
        </xs:key>
        <xs:key name="Khoakey">
            <xs:selector xpath="khoa"/>
            <xs:field xpath="ma"/>
        </xs:key>
        <xs:key name="SinhVienKey">
            <xs:selector xpath="sinhvien"/>
            <xs:field xpath="mssv"/>
        </xs:key>
        <xs:keyref name="ThuocLopRef" refer="LopKey">
            <xs:selector xpath="thuoc"/>
            <xs:field xpath="ma_lop_Ref"/>
        </xs:keyref>
        <xs:keyref name="ThuÃ³cinhVienRef" refer="SinhVienKey">
            <xs:selector xpath="thuoc"/>
            <xs:field xpath="mssv_Ref"/>
        </xs:keyref>
        <xs:keyref name="QuanLyLopRef" refer = "LopKey">
            <xs:selector xpath="quanly"/>
            <xs:field xpath="ma_lop_Ref"/>
        </xs:keyref>
        <xs:keyref name="QuanLyKhoaRef" refer="Khoakey">
            <xs:selector xpath="quanly"/>
            <xs:field xpath="ma_khoa_Ref"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== Locwara/CNXML_CN/BUOI_4/2/sv.xml
<?xml version="1.0" encoding="UTF-8"?>  
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sv.xsd">
    <sinhvien>
        <mssv>SV01</mssv>
        <hoten>Nguyễn Văn A</hoten>
        <email>nguyenvana@gmail.com</email>
        <diachi>Cần Thơ</diachi>
        <sdt>0476859943</sdt>
    </sinhvien>
    <sinhvien>
        <mssv>SV02</mssv>
        <hoten>Nguyễn Văn B</hoten>
        <email>nguyenvanb@gmail.com</email>
        <diachi>Cần Thơ</diachi>
        <sdt>0476435943</sdt>
    </sinhvien>
    <sinhvien>
        <mssv>SV03</mssv>
        <hoten>Nguyễn Văn c</hoten>
        <email>nguyenvanc@gmail.com</email>
        <diachi>Cần Thơ</diachi>
        <sdt>0476435943</sdt>
    </sinhvien>
    <lop>
        <ma>L001</ma>
        <ten>Công nghệ thông tin</ten>
    </lop>
    <lop>
        <ma>L002</ma>
        <ten>Khoa học dữ liệu</ten>
    </lop>
    <lop>
        <ma>L003</ma>
        <ten>Ngôn ngữ anh</ten>
    </lop>
    <khoa>
        <ma>K001</ma>
        <ten>CNTT</ten>
    </khoa>
    <khoa>
        <ma>K002</ma>
        <ten>KT</ten>
    </khoa>

    <thuoc>
        <mssv_Ref>SV01</mssv_Ref>
        <ma_lop_Ref>L001</ma_lop_Ref>
    </thuoc>
    <thuoc>
        <mssv_Ref>SV02</mssv_Ref>
        <ma_lop_Ref>L002</ma_lop_Ref>
    </thuoc>
    <thuoc>
        <mssv_Ref>SV03</mssv_Ref>
        <ma_lop_Ref>L003</ma_lop_Ref>
    </thuoc>

    <quanly>
        <ma_lop_Ref>L001</ma_lop_Ref>
        <ma_khoa_Ref>K001</ma_khoa_Ref>
    </quanly>
    <quanly>
        <ma_lop_Ref>L002</ma_lop_Ref>
        <ma_khoa_Ref>K002</ma_khoa_Ref>
    </quanly>
    <quanly>
        <ma_lop_Ref>L003</ma_lop_Ref>
        <ma_khoa_Ref>K002</ma_khoa_Ref>
    </quanly>
</school>
